### ISSUE TITLE
Update getTransactionByHash

### ISSUE THREAD

**Issue by avive** [karma-coin/karmacoin-app#13]
getTransactionByHash() should return a KC2Tx type and not a generic Transaction object.
Refactor tx processing code so we can create a KC2Tx from Transaction and uncouple it from tx processing for local user. Both use cases should use the same code to decode txs. The current tx processing code is tightly-coupled to local user tx processing logic.

**Comment by HolyGrease** [comment]
https://github.com/avive/karmacoin-app/pull/22
