### ISSUE TITLE
getKC2Trnsaction

### ISSUE THREAD

**Issue by avive** [karma-coin/karmacoin-app#15]
getKC2Trnsaction() should be able to decode all tx types and not only some of them

**Comment by HolyGrease** [comment]
We can implement this only hardcode all possible transactions and creating types for each possible transactions on chain. I think this is the waste of time and we need to focus on that transactions that users actually can submit in dart client.

**Comment by avive** [comment]
I agree. I meant only client submitted txs. I think we are missing the nomination ones but it can wait.

**Comment by HolyGrease** [comment]
https://github.com/avive/karmacoin-app/pull/21
