### ISSUE TITLE
Automate integration tests

### ISSUE THREAD

**Issue by avive** [karma-coin/karmacoin-app#16]
Write a script that runs all dart tests serially with one command.

**Comment by HolyGrease** [comment]
How is this suppose to be implemented? Just script that run `flutter test --name "test name"` and each of this command in parralel?

**Comment by HolyGrease** [comment]
There is no way to run several flutter test commands serially, in this case flutter wait to other command complete before. Message from flutter: `Waiting for another flutter command to release the startup lock...`

**Comment by HolyGrease** [comment]
So to run all tests serially we have to change global project architecture and allow to have several connections to chain. For me look likes it is plenty of work and it is not worth it

**Comment by avive** [comment]
not worth it. Let's delay this.
