### ISSUE TITLE
Dart API for search for users by name

### ISSUE THREAD

**Issue by avive** [karma-coin/karmacoin-app#9]
Provide dart api to search for users.
- Without suffix - return results with pagination for browsing.
- With string prefix - return matching results with pagination but consider suffix case insensitive so prefix 's' will also return user names that are prefixed with 'S'.

**Comment by HolyGrease** [comment]
Done in https://github.com/avive/karmacoin-app/commit/d9723f29743d5cda60bc80d74c8b53dc2dce6374
